api_platform:
    title: FAVES API
    version: 1.0.0
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 50
        pagination_items_per_page: 10
        pagination_enabled: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        normalization_context:
            skip_null_values: false
            
