lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_identity_field: id
    token_ttl: 86400 # Durée de validité du token en secondes (1 jour)

    # on utilise ça ou alors OpenApiFactory
    # api_platform:
    #     check_path: /api/login
    #     username_path: 'username'
    #     password_path: 'password'
        
